#mains
all: MiCasa.o

MiCasa.o: MenuPrincipal DatosYaCargados Manejadores
	g++ -o ./bin/MiCasa -Wall ./src/MiCasa.cpp ./lib/libTarea6.lib


#excepciones

DatosYaCargados:
	g++ -Wall -Werror -o ./obj/DatosYaCargados.o -c ./src/Excepciones/DatosYaCargados.cpp
	ar rvs ./lib/libTarea6.lib ./obj/DatosYaCargados.o
EdificioNoExistente:
	g++ -Wall -Werror -o ./obj/EdificioNoExistente.o -c ./src/Excepciones/EdificioNoExistente.cpp
	ar rvs ./lib/libTarea6.lib ./obj/EdificioNoExistente.o
ExDptoNoExistente:
	g++ -Wall -Werror -o ./obj/ExDptoNoExistente.o -c ./src/Excepciones/ExDptoNoExistente.cpp
	ar rvs ./lib/libTarea6.lib ./obj/ExDptoNoExistente.o
ExisteEdificio:
	g++ -Wall -Werror -o ./obj/ExisteEdificio.o -c ./src/Excepciones/ExisteEdificio.cpp
	ar rvs ./lib/libTarea6.lib ./obj/ExisteEdificio.o
ExisteInteresado:
	g++ -Wall -Werror -o ./obj/ExisteInteresado.o -c ./src/Excepciones/ExisteInteresado.cpp
	ar rvs ./lib/libTarea6.lib ./obj/ExisteInteresado.o
ExNoHayMensajes:
	g++ -Wall -Werror -o ./obj/ExNoHayMensajes.o -c ./src/Excepciones/ExNoHayMensajes.cpp
	ar rvs ./lib/libTarea6.lib ./obj/ExNoHayMensajes.o
ExNoHayZonas:
	g++ -Wall -Werror -o ./obj/ExNoHayZonas.o -c ./src/Excepciones/ExNoHayZonas.cpp
	ar rvs ./lib/libTarea6.lib ./obj/ExNoHayZonas.o
ExOpcionInvalida:
	g++ -Wall -Werror -o ./obj/ExOpcionInvalida.o -c ./src/Excepciones/ExOpcionInvalida.cpp
	ar rvs ./lib/libTarea6.lib ./obj/ExOpcionInvalida.o
ExPropiedadNoExistente:
	g++ -Wall -Werror -o ./obj/ExPropiedadNoExistente.o -c ./src/Excepciones/ExPropiedadNoExistente.cpp
	ar rvs ./lib/libTarea6.lib ./obj/ExPropiedadNoExistente.o
ExvaloresNoPositivos:
	g++ -Wall -Werror -o ./obj/ExvaloresNoPositivos.o -c ./src/Excepciones/ExvaloresNoPositivos.cpp
	ar rvs ./lib/libTarea6.lib ./obj/ExvaloresNoPositivos.o
FechaInvalida:
	g++ -Wall -Werror -o ./obj/FechaInvalida.o -c ./src/Excepciones/FechaInvalida.cpp
	ar rvs ./lib/libTarea6.lib ./obj/FechaInvalida.o
HoraInvalida:
	g++ -Wall -Werror -o ./obj/HoraInvalida.o -c ./src/Excepciones/HoraInvalida.cpp
	ar rvs ./lib/libTarea6.lib ./obj/HoraInvalida.o
InmobiliariaNotFound:
	g++ -Wall -Werror -o ./obj/InmobiliariaNotFound.o -c ./src/Excepciones/InmobiliariaNotFound.cpp
	ar rvs ./lib/libTarea6.lib ./obj/InmobiliariaNotFound.o
InmobiliariaYaExistente:
	g++ -Wall -Werror -o ./obj/InmobiliariaYaExistente.o -c ./src/Excepciones/InmobiliariaYaExistente.cpp
	ar rvs ./lib/libTarea6.lib ./obj/InmobiliariaYaExistente.o
InteresadoNotFound:
	g++ -Wall -Werror -o ./obj/InteresadoNotFound.o -c ./src/Excepciones/InteresadoNotFound.cpp
	ar rvs ./lib/libTarea6.lib ./obj/InteresadoNotFound.o
NoExisteChat:
	g++ -Wall -Werror -o ./obj/NoExisteChat.o -c ./src/Excepciones/NoExisteChat.cpp
	ar rvs ./lib/libTarea6.lib ./obj/NoExisteChat.o
NoExistenEdificios:
	g++ -Wall -Werror -o ./obj/NoExistenEdificios.o -c ./src/Excepciones/NoExistenEdificios.cpp
	ar rvs ./lib/libTarea6.lib ./obj/NoExistenEdificios.o
NoExisteZona:
	g++ -Wall -Werror -o ./obj/NoExisteZona.o -c ./src/Excepciones/NoExisteZona.cpp
	ar rvs ./lib/libTarea6.lib ./obj/NoExisteZona.o
NoHayChatEnMemoria:
	g++ -Wall -Werror -o ./obj/NoHayChatEnMemoria.o -c ./src/Excepciones/NoHayChatEnMemoria.cpp
	ar rvs ./lib/libTarea6.lib ./obj/NoHayChatEnMemoria.o
NoHayConversaciones:
	g++ -Wall -Werror -o ./obj/NoHayConversaciones.o -c ./src/Excepciones/NoHayConversaciones.cpp
	ar rvs ./lib/libTarea6.lib ./obj/NoHayConversaciones.o
NoHayDepartamentoEnMemoria:
	g++ -Wall -Werror -o ./obj/NoHayDepartamentoEnMemoria.o -c ./src/Excepciones/NoHayDepartamentoEnMemoria.cpp
	ar rvs ./lib/libTarea6.lib ./obj/NoHayDepartamentoEnMemoria.o
NoHayDepartamentos:
	g++ -Wall -Werror -o ./obj/NoHayDepartamentos.o -c ./src/Excepciones/NoHayDepartamentos.cpp
	ar rvs ./lib/libTarea6.lib ./obj/NoHayDepartamentos.o
NoHayPropiedades:
	g++ -Wall -Werror -o ./obj/NoHayPropiedades.o -c ./src/Excepciones/NoHayPropiedades.cpp
	ar rvs ./lib/libTarea6.lib ./obj/NoHayPropiedades.o
PrecioInvalido:
	g++ -Wall -Werror -o ./obj/PrecioInvalido.o -c ./src/Excepciones/PrecioInvalido.cpp
	ar rvs ./lib/libTarea6.lib ./obj/PrecioInvalido.o
ProcesoCancelado:
	g++ -Wall -Werror -o ./obj/ProcesoCancelado.o -c ./src/Excepciones/ProcesoCancelado.cpp
	ar rvs ./lib/libTarea6.lib ./obj/ProcesoCancelado.o
UsuarioNotFound:
	g++ -Wall -Werror -o ./obj/UsuarioNotFound.o -c ./src/Excepciones/UsuarioNotFound.cpp
	ar rvs ./lib/libTarea6.lib ./obj/UsuarioNotFound.o
ValoresInvalidos:
	g++ -Wall -Werror -o ./obj/ValoresInvalidos.o -c ./src/Excepciones/ValoresInvalidos.cpp
	ar rvs ./lib/libTarea6.lib ./obj/ValoresInvalidos.o
WrongPwd:
	g++ -Wall -Werror -o ./obj/WrongPwd.o -c ./src/Excepciones/WrongPwd.cpp
	ar rvs ./lib/libTarea6.lib ./obj/WrongPwd.o
YaExisteDepartamento:
	g++ -Wall -Werror -o ./obj/YaExisteDepartamento.o -c ./src/Excepciones/YaExisteDepartamento.cpp
	ar rvs ./lib/libTarea6.lib ./obj/YaExisteDepartamento.o
YaExistePropiedad:
	g++ -Wall -Werror -o ./obj/YaExistePropiedad.o -c ./src/Excepciones/YaExistePropiedad.cpp
	ar rvs ./lib/libTarea6.lib ./obj/YaExistePropiedad.o
YaExisteZona:
	g++ -Wall -Werror -o ./obj/YaExisteZona.o -c ./src/Excepciones/YaExisteZona.cpp
	ar rvs ./lib/libTarea6.lib ./obj/YaExisteZona.o

Excepciones: DatosYaCargados EdificioNoExistente ExDptoNoExistente ExisteEdificio ExisteInteresado ExNoHayMensajes ExNoHayZonas ExOpcionInvalida ExPropiedadNoExistente ExvaloresNoPositivos FechaInvalida HoraInvalida InmobiliariaNotFound InmobiliariaYaExistente InteresadoNotFound NoExisteChat NoExistenEdificios NoExisteZona NoHayChatEnMemoria NoHayConversaciones NoHayDepartamentoEnMemoria NoHayDepartamentos NoHayPropiedades PrecioInvalido ProcesoCancelado UsuarioNotFound ValoresInvalidos WrongPwd YaExisteDepartamento YaExistePropiedad YaExisteZona


#DataTypes
DataVenta:
	g++ -Wall -Werror -o ./obj/DataVenta.o -c ./src/DataTypes/DataVenta.cpp
	ar rvs ./lib/libTarea6.lib ./obj/DataVenta.o
DataZona:
	g++ -Wall -Werror -o ./obj/DataZona.o -c ./src/DataTypes/DataZona.cpp
	ar rvs ./lib/libTarea6.lib ./obj/DataZona.o
DtInteresado:
	g++ -Wall -Werror -o ./obj/DtInteresado.o -c ./src/DataTypes/DtInteresado.cpp
	ar rvs ./lib/libTarea6.lib ./obj/DtInteresado.o
Fecha: FechaInvalida
	g++ -Wall -Werror -o ./obj/Fecha.o -c ./src/DataTypes/Fecha.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Fecha.o
Hora: HoraInvalida
	g++ -Wall -Werror -o ./obj/Hora.o -c ./src/DataTypes/Hora.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Hora.o
DataAlquiler:
	g++ -Wall -Werror -o ./obj/DataAlquiler.o -c ./src/DataTypes/DataAlquiler.cpp
	ar rvs ./lib/libTarea6.lib ./obj/DataAlquiler.o
DataChat:
	g++ -Wall -Werror -o ./obj/DataChat.o -c ./src/DataTypes/DataChat.cpp
	ar rvs ./lib/libTarea6.lib ./obj/DataChat.o
DataDepartamento:
	g++ -Wall -Werror -o ./obj/DataDepartamento.o -c ./src/DataTypes/DataDepartamento.cpp
	ar rvs ./lib/libTarea6.lib ./obj/DataDepartamento.o
DataDetallePropiedad:
	g++ -Wall -Werror -o ./obj/DataDetallePropiedad.o -c ./src/DataTypes/DataDetallePropiedad.cpp
	ar rvs ./lib/libTarea6.lib ./obj/DataDetallePropiedad.o
DataEdificio:
	g++ -Wall -Werror -o ./obj/DataEdificio.o -c ./src/DataTypes/DataEdificio.cpp
	ar rvs ./lib/libTarea6.lib ./obj/DataEdificio.o
DataPropiedad: DataAlquiler DataVenta
	g++ -Wall -Werror -o ./obj/DataPropiedad.o -c ./src/DataTypes/DataPropiedad.cpp
	ar rvs ./lib/libTarea6.lib ./obj/DataPropiedad.o
DataApartamento: DataPropiedad
	g++ -Wall -Werror -o ./obj/DataApartamento.o -c ./src/DataTypes/DataApartamento.cpp
	ar rvs ./lib/libTarea6.lib ./obj/DataApartamento.o
DataCasa: DataPropiedad
	g++ -Wall -Werror -o ./obj/DataCasa.o -c ./src/DataTypes/DataCasa.cpp
	ar rvs ./lib/libTarea6.lib ./obj/DataCasa.o
DataReportePropiedad: DataZona DataDepartamento
	g++ -Wall -Werror -o ./obj/DataReportePropiedad.o -c ./src/DataTypes/DataReportePropiedad.cpp
	ar rvs ./lib/libTarea6.lib ./obj/DataReportePropiedad.o
DataInfoInmobiliaria: DataReportePropiedad
	g++ -Wall -Werror -o ./obj/DataInfoInmobiliaria.o -c ./src/DataTypes/DataInfoInmobiliaria.cpp
	ar rvs ./lib/libTarea6.lib ./obj/DataInfoInmobiliaria.o
DataInfoPropiedad:
	g++ -Wall -Werror -o ./obj/DataInfoPropiedad.o -c ./src/DataTypes/DataInfoPropiedad.cpp
	ar rvs ./lib/libTarea6.lib ./obj/DataInfoPropiedad.o
DataInmobiliaria:
	g++ -Wall -Werror -o ./obj/DataInmobiliaria.o -c ./src/DataTypes/DataInmobiliaria.cpp
	ar rvs ./lib/libTarea6.lib ./obj/DataInmobiliaria.o
DataMensaje: Hora Fecha
	g++ -Wall -Werror -o ./obj/DataMensaje.o -c ./src/DataTypes/DataMensaje.cpp
	ar rvs ./lib/libTarea6.lib ./obj/DataMensaje.o
DataReporteApartamento: DataReportePropiedad
	g++ -Wall -Werror -o ./obj/DataReporteApartamento.o -c ./src/DataTypes/DataReporteApartamento.cpp
	ar rvs ./lib/libTarea6.lib ./obj/DataReporteApartamento.o

DataReporteCasa: DataReportePropiedad
	g++ -Wall -Werror -o ./obj/DataReporteCasa.o -c ./src/DataTypes/DataReporteCasa.cpp
	ar rvs ./lib/libTarea6.lib ./obj/DataReporteCasa.o


DataTypes: DataVenta DataZona DtInteresado Fecha Hora DataAlquiler DataChat DataDepartamento DataDetallePropiedad DataEdificio DataPropiedad DataApartamento DataCasa DataReportePropiedad DataInfoInmobiliaria DataInfoPropiedad DataInmobiliaria DataMensaje DataReporteApartamento DataReporteCasa





Mensaje: DataMensaje Hora Fecha
	g++ -Wall -Werror -o ./obj/Mensaje.o -c ./src/ClasesDeDominio/Mensaje.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Mensaje.o
Usuario:
	g++ -Wall -Werror -o ./obj/Usuario.o -c ./src/ClasesDeDominio/Usuario.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Usuario.o
Sesion: Usuario
	g++ -Wall -Werror -o ./obj/Sesion.o -c ./src/ClasesDeDominio/Sesion.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Sesion.o
Administrador: Usuario
	g++ -Wall -Werror -o ./obj/Administrador.o -c ./src/ClasesDeDominio/Administrador.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Administrador.o
Alquiler: DataAlquiler
	g++ -Wall -Werror -o ./obj/Alquiler.o -c ./src/ClasesDeDominio/Alquiler.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Alquiler.o
Venta: DataVenta
	g++ -Wall -Werror -o ./obj/Venta.o -c ./src/ClasesDeDominio/Venta.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Venta.o
Inmobiliaria: Usuario Chat DataInfoInmobiliaria DataInmobiliaria NoExisteChat DataReportePropiedad
	g++ -Wall -Werror -o ./obj/Inmobiliaria.o -c ./src/ClasesDeDominio/Inmobiliaria.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Inmobiliaria.o
Interesado: Usuario Chat NoExisteChat DtInteresado
	g++ -Wall -Werror -o ./obj/Interesado.o -c ./src/ClasesDeDominio/Interesado.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Interesado.o
Propiedad: Chat Alquiler Venta DataInfoPropiedad DataReportePropiedad DataPropiedad DataDetallePropiedad
	g++ -Wall -Werror -o ./obj/Propiedad.o -c ./src/ClasesDeDominio/Propiedad.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Propiedad.o
Chat:  Mensaje DataChat ExNoHayMensajes
	g++ -Wall -Werror -o ./obj/Chat.o -c ./src/ClasesDeDominio/Chat.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Chat.o
Zona: DataZona Propiedad DataDepartamento NoHayPropiedades ExPropiedadNoExistente
	g++ -Wall -Werror -o ./obj/Zona.o -c ./src/ClasesDeDominio/Zona.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Zona.o
Departamento: ExNoHayZonas NoExisteZona YaExisteZona DataDepartamento Zona
	g++ -Wall -Werror -o ./obj/Departamento.o -c ./src/ClasesDeDominio/Departamento.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Departamento.o
Apartamento: Propiedad Oferta DataApartamento Zona DataReporteApartamento
	g++ -Wall -Werror -o ./obj/Apartamento.o -c ./src/ClasesDeDominio/Apartamento.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Apartamento.o
Casa: Propiedad Oferta DataCasa Zona DataReporteCasa
	g++ -Wall -Werror -o ./obj/Casa.o -c ./src/ClasesDeDominio/Casa.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Casa.o

Edificio: Apartamento DataEdificio ExvaloresNoPositivos
	g++ -Wall -Werror -o ./obj/Edificio.o -c ./src/ClasesDeDominio/Edificio.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Edificio.o

Oferta: Venta Alquiler Inmobiliaria Propiedad
	g++ -Wall -Werror -o ./obj/Oferta.o -c ./src/ClasesDeDominio/Oferta.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Oferta.o

Clases: Venta Usuario Sesion Administrador Alquiler Mensaje Interesado Departamento Zona Edificio Casa Chat Inmobiliaria Oferta Apartamento Propiedad

#controladores

UsuarioController: IUsuarioController Manejador_Usuario WrongPwd Sesion
	g++ -Wall -Werror -o ./obj/UsuarioController.o -c ./src/Controladores/UsuarioController.cpp
	ar rvs ./lib/libTarea6.lib ./obj/UsuarioController.o
PropiedadController: DataTypes IPropiedadController Clases Manejadores Excepciones
	g++ -Wall -Werror -o ./obj/PropiedadController.o -c ./src/Controladores/PropiedadController.cpp
	ar rvs ./lib/libTarea6.lib ./obj/PropiedadController.o
ModificarPropiedadController:IModificarPropiedadController DataPropiedad ProcesoCancelado Sesion Inmobiliaria ManejadorPropiedades
	g++ -Wall -Werror -o ./obj/ModificarPropiedadController.o -c ./src/Controladores/ModificarPropiedadController.cpp
	ar rvs ./lib/libTarea6.lib ./obj/ModificarPropiedadController.o
EnviarMensajeController:IEnviarMensajeController Clases Excepciones
	g++ -Wall -Werror -o ./obj/EnviarMensajeController.o -c ./src/Controladores/EnviarMensajeController.cpp
	ar rvs ./lib/libTarea6.lib ./obj/EnviarMensajeController.o
CargarDatosController: Clases ICargarDatosController Excepciones DataTypes Manejadores
	g++ -Wall -Werror -o ./obj/CargarDatosController.o -c ./src/Controladores/CargarDatosController.cpp
	ar rvs ./lib/libTarea6.lib ./obj/CargarDatosController.o

Controladores: PropiedadController UsuarioController EnviarMensajeController ModificarPropiedadController CargarDatosController




#manejadores
ManejadorDepartamentos: Departamento NoHayDepartamentos YaExisteDepartamento ExDptoNoExistente
	g++ -Wall -Werror -o ./obj/ManejadorDepartamentos.o -c ./src/Manejadores/ManejadorDepartamentos.cpp
	ar rvs ./lib/libTarea6.lib ./obj/ManejadorDepartamentos.o
Manejador_Usuario: Interesado Inmobiliaria Administrador InmobiliariaNotFound InteresadoNotFound UsuarioNotFound ExisteInteresado InmobiliariaYaExistente
	g++ -Wall -Werror -o ./obj/Manejador_Usuario.o -c ./src/Manejadores/Manejador_Usuario.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Manejador_Usuario.o
ManejadorEdificios: Edificio ExisteEdificio EdificioNoExistente NoExistenEdificios
	g++ -Wall -Werror -o ./obj/ManejadorEdificios.o -c ./src/Manejadores/ManejadorEdificios.cpp
	ar rvs ./lib/libTarea6.lib ./obj/ManejadorEdificios.o
ManejadorPropiedades: Propiedad Zona Oferta Edificio DataCasa DataApartamento Casa Apartamento ExPropiedadNoExistente
	g++ -Wall -Werror -o ./obj/ManejadorPropiedades.o -c ./src/Manejadores/ManejadorPropiedades.cpp
	ar rvs ./lib/libTarea6.lib ./obj/ManejadorPropiedades.o
Manejadores: ManejadorPropiedades ManejadorEdificios Manejador_Usuario ManejadorDepartamentos

#interfaces
IPropiedadController:
	g++ -Wall -Werror -o ./obj/IPropiedadController.o -c ./src/Interfaces/IPropiedadController.cpp
	ar rvs ./lib/libTarea6.lib ./obj/IPropiedadController.o
IUsuarioController:
	g++ -Wall -Werror -o ./obj/IUsuarioController.o -c ./src/Interfaces/IUsuarioController.cpp
	ar rvs ./lib/libTarea6.lib ./obj/IUsuarioController.o
ICargarDatosController:
	g++ -Wall -Werror -o ./obj/ICargarDatosController.o -c ./src/Interfaces/ICargarDatosController.cpp
	ar rvs ./lib/libTarea6.lib ./obj/ICargarDatosController.o
IEnviarMensajeController:
	g++ -Wall -Werror -o ./obj/IEnviarMensajeController.o -c ./src/Interfaces/IEnviarMensajeController.cpp
	ar rvs ./lib/libTarea6.lib ./obj/IEnviarMensajeController.o
IModificarPropiedadController:
	g++ -Wall -Werror -o ./obj/IModificarPropiedadController.o -c ./src/Interfaces/IModificarPropiedadController.cpp
	ar rvs ./lib/libTarea6.lib ./obj/IModificarPropiedadController.o

Interfaces: IPropiedadController IUsuarioController IEnviarMensajeController IModificarPropiedadController ICargarDatosController

#fabrica

Factory: PropiedadController UsuarioController EnviarMensajeController ModificarPropiedadController CargarDatosController
	g++ -Wall -Werror -o ./obj/Factory.o -c ./src/Fabrica/Factory.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Factory.o



#componentes ui

UserInterface :
	g++ -o ./obj/UserInterface.o -c ./src/Interfaces/UserInterface.cpp
	ar rvs ./lib/libTarea6.lib ./obj/UserInterface.o


#rutinas
RutinaAltaEdificio: Interfaces DataTypes MenuUtils Excepciones
	g++ -Wall -Werror -o ./obj/RutinaAltaEdificio.o -c ./src/Rutinas/RutinaAltaEdificio.cpp
	ar rvs ./lib/libTarea6.lib ./obj/RutinaAltaEdificio.o
RutinaAltaInmobiliaria: UserInterface DataTypes Excepciones Factory MenuUtils
	g++ -Wall -Werror -o ./obj/RutinaAltaInmobiliaria.o -c ./src/Rutinas/RutinaAltaInmobiliaria.cpp
	ar rvs ./lib/libTarea6.lib ./obj/RutinaAltaInmobiliaria.o
RutinaAltaInteresado: MenuUtils Interfaces DataTypes Excepciones Factory
	g++ -Wall -Werror -o ./obj/RutinaAltaInteresado.o -c ./src/Rutinas/RutinaAltaInteresado.cpp
	ar rvs ./lib/libTarea6.lib ./obj/RutinaAltaInteresado.o
RutinaConsultarPropiedad: Interfaces Excepciones DataTypes Factory MenuUtils
	g++ -Wall -Werror -o ./obj/RutinaConsultarPropiedad.o -c ./src/Rutinas/RutinaConsultarPropiedad.cpp
	ar rvs ./lib/libTarea6.lib ./obj/RutinaConsultarPropiedad.o
RutinaAltaPropiedad: MenuUtils DataTypes Excepciones Interfaces Factory RutinaConsultarPropiedad UserInterface
	g++ -Wall -Werror -o ./obj/RutinaAltaPropiedad.o -c ./src/Rutinas/RutinaAltaPropiedad.cpp
	ar rvs ./lib/libTarea6.lib ./obj/RutinaAltaPropiedad.o
RutinaCargarDatos: MenuUtils Factory Excepciones Interfaces
	g++ -Wall -Werror -o ./obj/RutinaCargarDatos.o -c ./src/Rutinas/RutinaCargarDatos.cpp
	ar rvs ./lib/libTarea6.lib ./obj/RutinaCargarDatos.o
RutinaCerrarSesion: Interfaces MenuUtils Menu Factory UserInterface
	g++ -Wall -Werror -o ./obj/RutinaCerrarSesion.o -c ./src/Rutinas/RutinaCerrarSesion.cpp
	ar rvs ./lib/libTarea6.lib ./obj/RutinaCerrarSesion.o
RutinaEliminarPropiedad: Interfaces Excepciones MenuUtils Factory
	g++ -Wall -Werror -o ./obj/RutinaEliminarPropiedad.o -c ./src/Rutinas/RutinaEliminarPropiedad.cpp
	ar rvs ./lib/libTarea6.lib ./obj/RutinaEliminarPropiedad.o
RutinaEnviarMensajeInmobiliaria: Interfaces Clases DataTypes Factory Excepciones MenuUtils
	g++ -Wall -Werror -o ./obj/RutinaEnviarMensajeInmobiliaria.o -c ./src/Rutinas/RutinaEnviarMensajeInmobiliaria.cpp
	ar rvs ./lib/libTarea6.lib ./obj/RutinaEnviarMensajeInmobiliaria.o

RutinaEnviarMensajeInteresado: Interfaces Clases DataTypes Factory Excepciones MenuUtils
	g++ -Wall -Werror -o ./obj/RutinaEnviarMensajeInteresado.o -c ./src/Rutinas/RutinaEnviarMensajeInteresado.cpp
	ar rvs ./lib/libTarea6.lib ./obj/RutinaEnviarMensajeInteresado.o

RutinaInicioSesion: Interfaces Manejadores Excepciones MenuUtils DataTypes Factory
	g++ -Wall -Werror -o ./obj/RutinaInicioSesion.o -c ./src/Rutinas/RutinaInicioSesion.cpp
	ar rvs ./lib/libTarea6.lib ./obj/RutinaInicioSesion.o
RutinaModificarPropiedad: Excepciones DataTypes Factory MenuUtils
	g++ -Wall -Werror -o ./obj/RutinaModificarPropiedad.o -c ./src/Rutinas/RutinaModificarPropiedad.cpp
	ar rvs ./lib/libTarea6.lib ./obj/RutinaModificarPropiedad.o
RutinaObtenerReporteInmobiliarias: Interfaces Manejadores Excepciones MenuUtils DataTypes Factory
	g++ -Wall -Werror -o ./obj/RutinaObtenerReporteInmobiliarias.o -c ./src/Rutinas/RutinaObtenerReporteInmobiliarias.cpp
	ar rvs ./lib/libTarea6.lib ./obj/RutinaObtenerReporteInmobiliarias.o

Rutinas :  RutinaAltaEdificio RutinaAltaInmobiliaria RutinaAltaInteresado RutinaAltaPropiedad RutinaCargarDatos RutinaCerrarSesion RutinaConsultarPropiedad RutinaEliminarPropiedad RutinaEnviarMensajeInmobiliaria RutinaEnviarMensajeInteresado RutinaInicioSesion RutinaModificarPropiedad RutinaObtenerReporteInmobiliarias

#menues
MenuUtils : Fecha
	g++ -Wall -Werror -o ./obj/MenuUtils.o -c ./src/Menus/MenuUtils.cpp
	ar rvs ./lib/libTarea6.lib ./obj/MenuUtils.o
Menu : UserInterface ExOpcionInvalida MenuUtils
	g++ -Wall -Werror -o ./obj/Menu.o -c ./src/Menus/Menu.cpp
	ar rvs ./lib/libTarea6.lib ./obj/Menu.o
MenuAdministradores : Menu RutinaAltaInmobiliaria RutinaCerrarSesion RutinaAltaInteresado Sesion
	g++ -Wall -Werror -o ./obj/MenuAdministradores.o -c ./src/Menus/MenuAdministradores.cpp
	ar rvs ./lib/libTarea6.lib ./obj/MenuAdministradores.o
MenuInmobiliarias : Menu Rutinas Sesion
	g++ -Wall -Werror -o ./obj/MenuInmobiliarias.o -c ./src/Menus/MenuInmobiliarias.cpp
	ar rvs ./lib/libTarea6.lib ./obj/MenuInmobiliarias.o
MenuInteresados : Menu RutinaConsultarPropiedad RutinaCerrarSesion RutinaEnviarMensajeInteresado Sesion
	g++ -Wall -Werror -o ./obj/MenuInteresados.o -c ./src/Menus/MenuInteresados.cpp
	ar rvs ./lib/libTarea6.lib ./obj/MenuInteresados.o
MenuPrincipal : Menu MenuInteresados MenuInmobiliarias MenuAdministradores RutinaInicioSesion Sesion Interesado Inmobiliaria Administrador
	g++ -Wall -Werror -o ./obj/MenuPrincipal.o -c ./src/Menus/MenuPrincipal.cpp
	ar rvs ./lib/libTarea6.lib ./obj/MenuPrincipal.o
Menues: Menu MenuUtils MenuAdministradores MenuInmobiliarias MenuInteresados MenuPrincipal


clean:
	rm ./obj/*.o
	rm ./bin/MiCasa
